### PR TITLE
Removing package in order to make server cmd compilable

### PR DESCRIPTION
**Pull request by ibuziuk**
Please, next time check whether your files compilable

### CODE REVIEW

**Comment by MolochkoVitaly** [comment]
Okey, I'll do it later.
17.04.2015 15:09 пользователь "Ilya Buziuk" notifications@github.com
написал:

**Comment by ibuziuk** [comment]
you can simply merge this PR - no need to redo anything

**Comment by MolochkoVitaly** [comment]
What is "this PR"?
17.04.2015 15:35 пользователь "Ilya Buziuk" notifications@github.com
написал:

**Comment by ibuziuk** [comment]
Just press "Merge pull request" button and you'll see

**Comment by ibuziuk** [comment]
Ok, you have done it manually. Closing

**Pull request closed without merging**
